[package]
name = "tetris-3d"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.99"

[lib]
crate-type = ["cdylib", "rlib"]
