name: CI

on:
  push:
    branches: 'main'
  workflow_dispatch:

jobs:
  update-db:
    runs-on: [self-hosted]
    steps:
      # Stop site to prevent interfering with the CI
      - run: sudo systemctl stop melsite

      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
        run: |
          bun --bun run build

      # Bring site back up again
      - run: sudo systemctl start melsite
