name: CI
permissions: read-all

on:
  push:
    branches: 'main'
  workflow_dispatch:

jobs:
  build_site:
    runs-on: [self-hosted]
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
        run: |
          bun --bun run build


      - name: Update site
        run: |
          sudo systemctl stop melsite
          rm ~/melsite-build -r
          cp ./node_modules ~/melsite-build/ -r
          cp ./build ~/melsite-build/ -r
          sudo systemctl start melsite
