name: CI
permissions: read-all

on:
  push:
    branches: 'main'
  workflow_dispatch:

jobs:
  build_site:
    runs-on: [self-hosted]
    steps:
      # Stop site to prevent interfering with the CI
      - run: sudo systemctl stop melsite

      - uses: actions/setup-node@v4

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
        run: |
          npm run build

      # Bring site back up again
      - run: sudo systemctl start melsite
