name: CI

on:
  push:
    branches: 'main'
  workflow_dispatch:

jobs:
  build_site:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          bun --bun run build

      # Because of some sudoers shenanigans this should work fine...?
      - run: sudo systemctl restart melsite
