name: Update DB

on:
  push:
    paths:
      - prisma/migrations/** # Only run this workflow when migrations are updated
    branches: 'main'
  workflow_dispatch:

jobs:
  build_site:
    runs-on: [self-hosted]
    steps:
      # Stop site to prevent interfering with the migration
      - run: sudo systemctl stop melsite

      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Migrate database
        run: bunx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Bring site back up again
      - run: sudo systemctl start melsite