name: Update DB
permissions: read-all

on:
  push:
    paths:
      - prisma/migrations/** # Only run this workflow when migrations are updated
    branches: 'main'
  workflow_dispatch:

jobs:
  update-db:
    runs-on: [self-hosted]
    steps:
      # Stop site to prevent interfering with the migration
      - run: sudo systemctl stop melsite

      - uses: actions/setup-node@v4

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Migrate database
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Bring site back up again
      - run: sudo systemctl start melsite